import Head from 'next/head'
import { GetServerSidePropsResult, NextPage } from 'next'
import { useTranslation } from 'next-i18next'

// config
import { AppConfig } from '@/features/app/config'

// @mui
import Box from '@mui/material/Box'
import Typography from '@mui/material/Typography'
import { Button, Iconify } from '@/components/core'

// Next
const HomePage: NextPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>{AppConfig.AppName}</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Box>
        <Typography gutterBottom>{AppConfig.AppName}</Typography>
        <Button disableRipple endIcon={<Iconify icon='solar:arrow-right-bold-duotone' />} variant='contained' size='medium'>
          Click Me
        </Button>
      </Box>
    </>
  )
}

export default HomePage
