import Head from 'next/head'
import { GetServerSidePropsResult, NextPage } from 'next'
import { useTranslation } from 'next-i18next'

// config
import { AppConfig } from '@/features/app/config'

// @mui
import Box from '@mui/material/Box'
import Typography from '@mui/material/Typography'

// Next
const HomePage: NextPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>{AppConfig.AppName}</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Box>
        <Typography>{AppConfig.AppName}</Typography>
      </Box>
    </>
  )
}

export default HomePage
